import './globals.css'
import { Kumbh_Sans } from 'next/font/google'

const kumbhSans = Kumbh_Sans({ weight: ['400','700'],
subsets: ['latin'], })

export const metadata = {
  title: 'Officelite',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kumbhSans.className}>{children}</body>
    </html>
  )
}
